package com.invalidname.spawnerblocks;

import dangerzone.StuffList;
import dangerzone.blocks.Blocks;
import dangerzone.items.Items;

public class LootTables {
	
	public static StuffList[] surface_loot = new StuffList[] {
			new StuffList(Items.coinsilver, 5, 25, 35),
			new StuffList(Items.pistol, 1, 1, 15),
			new StuffList(Items.bullets, 4, 8, 25),
			new StuffList(Items.woodenaxe, 1, 1, 20),
			new StuffList(Items.woodenshovel, 1, 1, 20),
			new StuffList(Items.woodenhoe, 1, 1, 20),
			new StuffList(Items.woodenpickaxe, 1, 1, 20),
			new StuffList(Items.woodensword, 1, 1, 20),
			new StuffList(Items.furball, 1, 10, 50),
			new StuffList(Items.furball, 1, 10, 50),
			new StuffList(Items.furball, 1, 10, 50),
			new StuffList(Items.furball, 1, 10, 50),
			new StuffList(Items.instability, 1, 8, 15),
			new StuffList(Items.corn, 1, 12, 35),
			new StuffList(Items.corn, 1, 8, 35),
			new StuffList(Items.radish, 1, 12, 35),
			new StuffList(Items.radish, 1, 6, 35),
			new StuffList(Items.moosemeat, 1, 4, 45),
			new StuffList(Items.moosebone, 1, 8, 45),
			new StuffList(Items.goosemeat, 1, 8, 45),
			new StuffList(Items.copperhelmet, 1, 1, 1),
			new StuffList(Items.copperchestplate, 1, 1, 1),
			new StuffList(Items.copperleggings, 1, 1, 1),
			new StuffList(Items.copperboots, 1, 1, 1),
			new StuffList(Items.firestick, 1, 1, 25),
			new StuffList(Items.deadbug, 1, 10, 40),
			new StuffList(Items.peachseed, 1, 10, 40),
			new StuffList(Items.appleseed, 1, 6, 45),
			new StuffList(Items.cherryseed, 1, 8, 45),
			new StuffList(Items.dark, 1, 9, 15),
			new StuffList(Items.light, 1, 9, 15),
			new StuffList(Items.bottle, 1, 5, 35),
			new StuffList(Items.experiencebottle, 1, 4, 5),
			new StuffList(Items.bread, 1, 4, 45),
			new StuffList(Items.rice, 1, 6, 45),
			new StuffList(Items.eggbutterfly, 1, 6, 15),
			new StuffList(Items.eggghost, 1, 6, 15),
			new StuffList(Items.eggghostskelly, 1, 6, 15),
			new StuffList(Items.eggrat, 1, 6, 15),
			new StuffList(Items.eggcockroach, 1, 6, 15),
			new StuffList(Items.egggosling, 1, 6, 15),
			new StuffList(Items.frog_speed1, 1, 6, 10),
			new StuffList(Items.frog_slowness1, 1, 6, 10),
			new StuffList(Items.frog_slowness2, 1, 6, 10),
			new StuffList(Items.frog_strength1, 1, 6, 10),
			new StuffList(Items.frog_weakness1, 1, 6, 10),
			new StuffList(Items.frog_weakness2, 1, 6, 10),
			new StuffList(Items.frog_weakness3, 1, 6, 10),		
			new StuffList(Items.frog_regen1, 1, 6, 15),
			new StuffList(Items.frog_poison1, 1, 6, 15),
			new StuffList(Items.frog_poison2, 1, 6, 15),
			new StuffList(Items.frog_confusion1, 1, 6, 15),
			new StuffList(Items.frog_morph1, 1, 6, 15),
			new StuffList(Blocks.stand, 5, 10, 15),
			new StuffList(Blocks.stone, 1, 5, 10),
			new StuffList(Blocks.greystone, 1, 5, 10),
			new StuffList(Blocks.lightstick, 1, 16, 40),
			new StuffList(Blocks.darkstick, 1, 16, 10),
			new StuffList(Blocks.blocklight, 1, 1, 1),
			new StuffList(Blocks.blockdark, 1, 1, 1),
			new StuffList(Blocks.blockcopper, 1, 1, 1),
			new StuffList(Blocks.blocktin, 1, 1, 1),
			new StuffList(Blocks.log, 5, 10, 25),
			new StuffList(Blocks.willowlog, 5, 10, 25),
			new StuffList(Blocks.redwoodlog, 5, 10, 25),
			new StuffList(Blocks.stopblock, 1, 5, 1),
			new StuffList(Items.getItem(Items.findByName("SpawnerBlocks:Giant Stick")), 1, 1, 2),
			new StuffList(Items.getItem(Items.findByName("SpawnerBlocks:Giant Wooden Sword")), 1, 1, 5),
			new StuffList(Items.getItem(Items.findByName("SpawnerBlocks:Giant Wooden Pickaxe")), 1, 1, 5),
			new StuffList(Items.getItem(Items.findByName("SpawnerBlocks:Giant Wooden Axe")), 1, 1, 5),
			new StuffList(Items.getItem(Items.findByName("SpawnerBlocks:Giant Wooden Shovel")), 1, 1, 5),
			new StuffList(Items.getItem(Items.findByName("SpawnerBlocks:Giant Stone Sword")), 1, 1, 1),
			new StuffList(Items.getItem(Items.findByName("SpawnerBlocks:Giant Stone Pickaxe")), 1, 1, 1),
			new StuffList(Items.getItem(Items.findByName("SpawnerBlocks:Giant Stone Axe")), 1, 1, 1),
			new StuffList(Items.getItem(Items.findByName("SpawnerBlocks:Giant Stone Shovel")), 1, 1, 1),
			new StuffList(Items.getItem(Items.findByName("SpawnerBlocks:Spawn BUTTERfly")), 1, 8, 35),
			new StuffList(Items.getItem(Items.findByName("SpawnerBlocks:Ammo")), 1, 4, 25)
	};
	
	public static StuffList[] dungeon_medium = new StuffList[] {
			
	};
}
