// Date: 21/11/2020 14:47:44
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.invalidname.spawnerblocks.entities;

import dangerzone.ModelBase;
import dangerzone.ModelRenderer;
import dangerzone.entities.Entity;

public class ModelButterFly extends ModelBase {
	
	//fields
	ModelRenderer Body;
	ModelRenderer LeftBackWing;
	ModelRenderer LeftFrontWing;
	ModelRenderer RightBackWing;
	ModelRenderer RightFrontWing;
	
	public ModelButterFly() {
		
		
		Body = new ModelRenderer(this, 0, 0);
		Body.addBox(-4F, -3F, -6F, 8, 6, 12);
		Body.setRotationPoint(0F, 18F, 0F);
		Body.setTextureSize(128, 32);
		Body.mirror = true;
		setRotation(Body, 0F, 0F, 0F);
		LeftBackWing = new ModelRenderer(this, 40, 13);
		LeftBackWing.addBox(0F, -1F, 0F, 8, 1, 12);
		LeftBackWing.setRotationPoint(1F, 15F, 0F);
		LeftBackWing.setTextureSize(128, 32);
		LeftBackWing.mirror = true;
		setRotation(LeftBackWing, 0F, 0F, 0F);
		LeftFrontWing = new ModelRenderer(this, 80, 15);
		LeftFrontWing.addBox(0F, -1F, -14F, 10, 1, 14);
		LeftFrontWing.setRotationPoint(1F, 15F, 0F);
		LeftFrontWing.setTextureSize(128, 32);
		LeftFrontWing.mirror = true;
		setRotation(LeftFrontWing, 0F, 0F, 0F);
		RightBackWing = new ModelRenderer(this, 40, 0);
		RightBackWing.addBox(-8F, -1F, 0F, 8, 1, 12);
		RightBackWing.setRotationPoint(-1F, 15F, 0F);
		RightBackWing.setTextureSize(128, 32);
		RightBackWing.mirror = true;
		setRotation(RightBackWing, 0F, 0F, 0F);
		RightFrontWing = new ModelRenderer(this, 80, 0);
		RightFrontWing.addBox(-10F, -1F, -14F, 10, 1, 14);
		RightFrontWing.setRotationPoint(-1F, 15F, 0F);
		RightFrontWing.setTextureSize(128, 32);
		RightFrontWing.mirror = true;
		setRotation(RightFrontWing, 0F, 0F, 0F);
	}
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float deathfactor) {   
		float newangle = 0;
		
		newangle = (float) (Math.cos(Math.toRadians(f*19.3f)) * (float)Math.PI * 0.25F+Math.toRadians(45.0f));
		
		this.RightBackWing.rotateAngleZ = newangle;
		this.RightFrontWing.rotateAngleZ = this.RightBackWing.rotateAngleZ;
		this.LeftBackWing.rotateAngleZ = -this.RightBackWing.rotateAngleZ;
		this.LeftFrontWing.rotateAngleZ = -this.RightBackWing.rotateAngleZ;
		
		Body.render(deathfactor);
		LeftBackWing.render(deathfactor);
		LeftFrontWing.render(deathfactor);
		RightBackWing.render(deathfactor);
		RightFrontWing.render(deathfactor);
	}
}
